### ISSUE TITLE
command 'filterLines.filterLines' not found

### ISSUE THREAD

**Issue by yihualu** [earshinov/vscode-filter-lines#11]
when I was trying to create a key binding, got "command 'filterLines.filterLines' not found"
while "filterlines.promptFilterLines" works.

**Comment by earshinov** [comment]
Hmm... Seems to be working for me with this shortcut configuration:

```
{
    "key": "ctrl+alt+shift+z",
    "command": "filterlines.filterLines",
    "args": {
        "needle": "test",
    },
    "when": "editorTextFocus"
}
```

**Comment by earshinov** [comment]
Closing as stale
