### ISSUE TITLE
Folding should not happen not filtering with context

### ISSUE THREAD

**Issue by baincd** [earshinov/vscode-filter-lines#9]
Lines should not be folded in the following scenarios (even if `foldIndentedContext` is true)

- When executing one of the commands that does not include context
- When executing one of the "...and Context" commands but with a context of 0

**Comment by earshinov** [comment]
Makes sense. I will fix it within a few days. Thanks for reporting!

**Comment by earshinov** [comment]
@baincd , I just checked and it seems that `foldIndentedContext` already works as you described. Can you please provide detailed repro steps:

- Content of the file your are filtering
- Your `filterlines` VS Code settings
- Commands you execute
- Actual and expected outcome

?

**Comment by baincd** [comment]
Hi @earshinov ,

Sure, no problem.  Using the default settings (and other extensions disabled)
![image](https://user-images.githubusercontent.com/5075659/116795209-3f192080-aaa1-11eb-8abe-813eb18efa15.png)

When executing the "Exclude Lines with RegEx", after filtering the contents are folded  
![](https://user-images.githubusercontent.com/5075659/116795499-6bce3780-aaa3-11eb-9077-ba20daf0e8b1.png)

I expected the file to not be folded (folding should happen only when using one of the "...and Context" commands)

The folding occurs (but should not):
- For all 4 commands that do not include context
- For either value of "Filter Lines: Create New Tab" setting

Thanks!

**Comment by earshinov** [comment]
Should be fixed in v1.0.0. Please let me know if you have any problems.

**Comment by baincd** [comment]
Perfect, thank you!
